/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTicketsRouteImport } from './routes/_app.tickets'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppAiChatRouteImport } from './routes/_app.ai-chat'
import { Route as AppTicketsIdRouteImport } from './routes/_app.tickets.$id'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppAdminStoresRouteImport } from './routes/_app.admin.stores'
import { Route as AppAdminStatesRouteImport } from './routes/_app.admin.states'
import { Route as AppAdminMarketsRouteImport } from './routes/_app.admin.markets'
import { Route as AppAdminHousesRouteImport } from './routes/_app.admin.houses'
import { Route as AppAdminExternalRouteImport } from './routes/_app.admin.external'
import { Route as AppAdminDistrictsRouteImport } from './routes/_app.admin.districts'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTicketsRoute = AppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAiChatRoute = AppAiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsIdRoute = AppTicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTicketsRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminStoresRoute = AppAdminStoresRouteImport.update({
  id: '/admin/stores',
  path: '/admin/stores',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminStatesRoute = AppAdminStatesRouteImport.update({
  id: '/admin/states',
  path: '/admin/states',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminMarketsRoute = AppAdminMarketsRouteImport.update({
  id: '/admin/markets',
  path: '/admin/markets',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminHousesRoute = AppAdminHousesRouteImport.update({
  id: '/admin/houses',
  path: '/admin/houses',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminExternalRoute = AppAdminExternalRouteImport.update({
  id: '/admin/external',
  path: '/admin/external',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDistrictsRoute = AppAdminDistrictsRouteImport.update({
  id: '/admin/districts',
  path: '/admin/districts',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ai-chat': typeof AppAiChatRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/tickets': typeof AppTicketsRouteWithChildren
  '/admin/districts': typeof AppAdminDistrictsRoute
  '/admin/external': typeof AppAdminExternalRoute
  '/admin/houses': typeof AppAdminHousesRoute
  '/admin/markets': typeof AppAdminMarketsRoute
  '/admin/states': typeof AppAdminStatesRoute
  '/admin/stores': typeof AppAdminStoresRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/tickets/$id': typeof AppTicketsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ai-chat': typeof AppAiChatRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/tickets': typeof AppTicketsRouteWithChildren
  '/admin/districts': typeof AppAdminDistrictsRoute
  '/admin/external': typeof AppAdminExternalRoute
  '/admin/houses': typeof AppAdminHousesRoute
  '/admin/markets': typeof AppAdminMarketsRoute
  '/admin/states': typeof AppAdminStatesRoute
  '/admin/stores': typeof AppAdminStoresRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/tickets/$id': typeof AppTicketsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/ai-chat': typeof AppAiChatRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tickets': typeof AppTicketsRouteWithChildren
  '/_app/admin/districts': typeof AppAdminDistrictsRoute
  '/_app/admin/external': typeof AppAdminExternalRoute
  '/_app/admin/houses': typeof AppAdminHousesRoute
  '/_app/admin/markets': typeof AppAdminMarketsRoute
  '/_app/admin/states': typeof AppAdminStatesRoute
  '/_app/admin/stores': typeof AppAdminStoresRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/tickets/$id': typeof AppTicketsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/ai-chat'
    | '/chat'
    | '/dashboard'
    | '/settings'
    | '/tickets'
    | '/admin/districts'
    | '/admin/external'
    | '/admin/houses'
    | '/admin/markets'
    | '/admin/states'
    | '/admin/stores'
    | '/admin/users'
    | '/tickets/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/ai-chat'
    | '/chat'
    | '/dashboard'
    | '/settings'
    | '/tickets'
    | '/admin/districts'
    | '/admin/external'
    | '/admin/houses'
    | '/admin/markets'
    | '/admin/states'
    | '/admin/stores'
    | '/admin/users'
    | '/tickets/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_app/ai-chat'
    | '/_app/chat'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/_app/tickets'
    | '/_app/admin/districts'
    | '/_app/admin/external'
    | '/_app/admin/houses'
    | '/_app/admin/markets'
    | '/_app/admin/states'
    | '/_app/admin/stores'
    | '/_app/admin/users'
    | '/_app/tickets/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tickets': {
      id: '/_app/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AppTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-chat': {
      id: '/_app/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AppAiChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tickets/$id': {
      id: '/_app/tickets/$id'
      path: '/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof AppTicketsIdRouteImport
      parentRoute: typeof AppTicketsRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/stores': {
      id: '/_app/admin/stores'
      path: '/admin/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AppAdminStoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/states': {
      id: '/_app/admin/states'
      path: '/admin/states'
      fullPath: '/admin/states'
      preLoaderRoute: typeof AppAdminStatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/markets': {
      id: '/_app/admin/markets'
      path: '/admin/markets'
      fullPath: '/admin/markets'
      preLoaderRoute: typeof AppAdminMarketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/houses': {
      id: '/_app/admin/houses'
      path: '/admin/houses'
      fullPath: '/admin/houses'
      preLoaderRoute: typeof AppAdminHousesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/external': {
      id: '/_app/admin/external'
      path: '/admin/external'
      fullPath: '/admin/external'
      preLoaderRoute: typeof AppAdminExternalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/districts': {
      id: '/_app/admin/districts'
      path: '/admin/districts'
      fullPath: '/admin/districts'
      preLoaderRoute: typeof AppAdminDistrictsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppTicketsRouteChildren {
  AppTicketsIdRoute: typeof AppTicketsIdRoute
}

const AppTicketsRouteChildren: AppTicketsRouteChildren = {
  AppTicketsIdRoute: AppTicketsIdRoute,
}

const AppTicketsRouteWithChildren = AppTicketsRoute._addFileChildren(
  AppTicketsRouteChildren,
)

interface AppRouteChildren {
  AppAiChatRoute: typeof AppAiChatRoute
  AppChatRoute: typeof AppChatRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTicketsRoute: typeof AppTicketsRouteWithChildren
  AppAdminDistrictsRoute: typeof AppAdminDistrictsRoute
  AppAdminExternalRoute: typeof AppAdminExternalRoute
  AppAdminHousesRoute: typeof AppAdminHousesRoute
  AppAdminMarketsRoute: typeof AppAdminMarketsRoute
  AppAdminStatesRoute: typeof AppAdminStatesRoute
  AppAdminStoresRoute: typeof AppAdminStoresRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiChatRoute: AppAiChatRoute,
  AppChatRoute: AppChatRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTicketsRoute: AppTicketsRouteWithChildren,
  AppAdminDistrictsRoute: AppAdminDistrictsRoute,
  AppAdminExternalRoute: AppAdminExternalRoute,
  AppAdminHousesRoute: AppAdminHousesRoute,
  AppAdminMarketsRoute: AppAdminMarketsRoute,
  AppAdminStatesRoute: AppAdminStatesRoute,
  AppAdminStoresRoute: AppAdminStoresRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
